### ISSUE TITLE
AmbiguousMatchException with PresentationDocument

### ISSUE THREAD

**Issue by stevenmoberg** [rmboggs/Serialize.OpenXml.CodeGen#2] opened 2020-10-31 02:03 UTC
Hello, testing with a very simple PPTX and getting a AmbiguousMatchExpression exception with the call to GenerateSourceCode()

`
at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)   at System.Type.GetMethod(String name)   at Serialize.OpenXml.CodeGen.OpenXmlPartExtensions.BuildEntryMethodCodeStatements(IdPartPair part, NamespaceAliasOptions opts, IDictionary`2 typeCounts, ISet`1 namespaces, OpenXmlPartBluePrintCollection blueprints, KeyValuePair`2 rootVar)   at Serialize.OpenXml.CodeGen.OpenXmlPartExtensions.BuildEntryMethodCodeStatements(IdPartPair part, NamespaceAliasOptions opts, IDictionary`2 typeCounts, ISet`1 namespaces, OpenXmlPartBluePrintCollection blueprints, KeyValuePair`2 rootVar)   at Serialize.OpenXml.CodeGen.OpenXmlPackageExtensions.GenerateSourceCode(OpenXmlPackage pkg, NamespaceAliasOptions opts)   at Serialize.OpenXml.CodeGen.OpenXmlPackageExtensions.GenerateSourceCode(OpenXmlPackage pkg)
`

Is this is known issue or would it be related to running in LinqPad?

**Comment by rmboggs** [comment] 2020-11-04 20:20
Hi, sorry for the delay.

This shouldn't be related to linqpad.

Looking at the error msg, it looks like there is a conflict with the type names being used. Most likely from 2 types in 2 different namespaces but with the same name that i was not aware of. This scenario is mostly common with pptx and docx files.  

Can you share the file in question so i can debug and see what I can do?  Also, are you using the latest source or what is in nuget today? There may be a possibility that i haven't pushed this fix to nuget yet.

**Comment by stevenmoberg** [comment] 2020-11-06 01:30
[samplepptx.pptx](https://github.com/rmboggs/Serialize.OpenXml.CodeGen/files/5498355/samplepptx.pptx)

Here is a very simply pptx I got off the internet that has the same ambiguous exception

**Comment by rmboggs** [comment] 2020-11-06 18:40
Ok, the most current release is 0.3.2-alpha here and in nuget.  You may have not seen it in nuget because it is still considered a prerelease.

Also,
Looking at the project [changelog](https://github.com/rmboggs/Serialize.OpenXml.CodeGen/blob/master/CHANGELOG.md), it looks like I fixed an ambiguous exception issue with the 0.3.0-alpha release.  I'm going to make sure that the latest release is available here (looks like I haven't updated github in awhile, my fault).  Can you check your office document file against the 0.3.2-alpha release and see if the exception still occurs?

**Comment by rmboggs** [comment] 2020-11-06 20:52
[This release - v0.3.2-alpha](https://github.com/rmboggs/Serialize.OpenXml.CodeGen/releases/tag/0.3.2-alpha) should fix this issue.  Please let me know what you find.

**Comment by rmboggs** [comment] 2020-11-12 16:05
I can confirm that the `AmbiguousMatchException` does not occur with the latest version, 0.3.2-alpha, using the referenced file in this issue. I will close this issue later today unless there are any further followups.

**Comment by rmboggs** [comment] 2020-11-13 17:40
Closing issue because fix has already been applied to main branch.

**Closed** 2020-11-13 17:40 UTC

**Comment by stevenmoberg** [comment] 2020-11-15 20:56
yes that fixed the issue.
I was trying to make sense of what it generated and forgot to reply, sorry
